# NumPy
---

## Основы NumPy

**Основы NumPy** - это объект **ndarray**, который используется для представления **N-мерного массива**; это быстрый и гибкий контейнер для хранения больших наборов данных в Python. Массивы позволяют выполнять математические операции над целыми блоками данных. По сути это обычный list с большим набором возможностей.

У любого **numpy-массива (array)** есть атрибут **shape** - кортеж, описывающий размер по каждому измерению, и атрибут **dtype**- объект, описывающий тип данных в массиве; **ndim** - количество измерений массива (одномерный, двумерный и т.д.); **tolist()** - конвертирует array в обычный python list.

**Array vs list:**
* Array использует меньше памяти, чем списки
* Array обладают значительно большей функциональностью
* Array требуют, чтобы данные были однородными; списки нет

### 1D (одномерные массивы, списки, векторы); 2D (двумерные массивы, матрицы) и 3D (куб)-arrays:
![N-Arrays](https://i.stack.imgur.com/NWTQH.png)

Четырехмерный, пятимерный и более массив - это **тензор**.

## Работа с NumPy

In [1]:
import numpy as np

### Одномерные массивы

#### Создание Array

Создание из list

In [2]:
data = [1, 2, 3, 4, 5]

arr = np.array(data)

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
(5,)
int64
1


**Типы данных NumPy:**
* np.int64      // Signed 64-bit integer types
* np.float32    // Standard double-precision floating point
* np.complex    // Complex numbers represented by 128 floats
* np.bool       // Boolean type storing TRUE and FALSE values
* np.object     // Python object type
* np.string_    // Fixed-length string type
* np.unicode_   // Fixed-length unicode type

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr = np.array([1,2,3,4,5], dtype=np.float64)

print(len(arr))
print(arr.size)
arr

5
5


array([1., 2., 3., 4., 5.])

Приводим все элементы к типу int64

In [6]:
arr = arr.astype(np.int64)

print(arr.dtype)
arr

int64


array([1, 2, 3, 4, 5])

Генерация от 0 до 20 с шагом 1.5

In [7]:
arr = np.arange(0, 20, 1.5)
arr

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

Создание 5 числе равноудаленных друг от друга в отрезке [0, 2]

In [9]:
arr = np.linspace(0, 2, 5)
arr

array([0. , 0.5, 1. , 1.5, 2. ])

In [33]:
arr = np.random.random((5,))
arr = np.random.random_sample((5,))
arr = np.random.randint(-5, 10, 10)
arr

array([ 3, -5, -3,  1,  1,  5,  4, -4, -1,  3])

Диапазон случайных чисел от [a,b]: (b-a) * np.random() + a, где b > a

In [16]:
# 5 случайных значений от -5 до 10
arr = (10 - -5) * np.random.random_sample((5,)) + -5
arr

array([-1.22092117,  1.02811722,  9.04812667,  3.61682309, -4.74971996])

#### Операции

In [21]:
a = np.arange(1, 6)
b = np.arange(6, 11)

In [23]:
np.add(a, b)
a + b

array([ 7,  9, 11, 13, 15])

In [25]:
np.subtract(a, b)
a - b

array([-5, -5, -5, -5, -5])

In [26]:
np.multiply(a, b)
a * b

array([ 6, 14, 24, 36, 50])

In [27]:
np.divide(a, b)
a / b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [30]:
print(a * 2)
print(b ** 2)

[ 2  4  6  8 10]


array([ 36,  49,  64,  81, 100])

In [31]:
arr = np.arange(1,5)

arr = np.sqrt(arr)
print(arr)

arr = np.sin(arr)
print(arr)

arr = np.cos(arr)
print(arr)

arr = np.log(arr)
print(arr)

arr = np.exp(arr)
print(arr)

[1.         1.41421356 1.73205081 2.        ]
[0.84147098 0.98776595 0.98702664 0.90929743]
[0.66636675 0.55055622 0.55117323 0.61430028]
[-0.40591509 -0.59682621 -0.59570612 -0.48727141]
[0.66636675 0.55055622 0.55117323 0.61430028]


#### Функции и агрегаты

In [36]:
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.sum())
print(arr.std())
print(np.median(arr))

[ 3 -5 -3  1  1  5  4 -4 -1  3]
5
-5
0.4
4
3.32264954516723
1.0


In [37]:
arr < 2

array([False,  True,  True,  True,  True, False, False,  True,  True,
       False])

#### Манипуляции с массивами

In [118]:
np.append(arr, np.array([1,2,3])) # добавляем 1, 2, 3

array([0, 0, 0, 0, 5, 1, 2, 3])

In [40]:
np.insert(arr, 2, -20) # Вставляем -20 в позицию 2

array([  3,  -5, -20,  -3,   1,   1,   5,   4,  -4,  -1,   3])

In [41]:
np.delete(arr, 2) # удаляем элемент во 2 позиции, с матрицами можно указывать строки или стобцы

array([ 3, -5,  1,  1,  5,  4, -4, -1,  3])

In [46]:
np.sort(arr)    # returns copy
arr.sort()      # sort inplace
arr

array([-5, -4, -3, -1,  1,  1,  3,  3,  4,  5])

In [47]:
arr = np.concatenate((arr, b))
arr

array([-5, -4, -3, -1,  1,  1,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.array_split(arr, 3) # hsplit, vsplit

[array([-5, -4, -3, -1,  1]),
 array([1, 3, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10])]

#### Индексы и одномерные массивы

In [49]:
arr = np.array([1, -2, 3, -4, 5])
arr[0] = 0
print(arr[2])
print(arr[0:2])
print(arr[::-1])
print(arr[arr < 2])
print(arr[(arr < 2) & (arr > 0)])
print(arr[(arr > 4) | (arr < 0)])
arr[1:4] = 0
print(arr)

3
[ 0 -2]
[ 5 -4  3 -2  0]
[ 0 -2 -4]
[]
[-2 -4  5]
[0 0 0 0 5]


### Матрицы и многомерные массивы

#### Создание и базовые свойства

In [54]:
matrix = np.array([(1,2,3), (4,5,6)], dtype=np.float64)
matrix = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
matrix = np.array([(1,2,3), (4,5,6), (7,8,9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
print("shape:", matrix.shape)
print("size:", matrix.size)
print("len:", len(matrix))
print(matrix.ndim)

shape: (3, 3)
size: 9
len: 3
2


In [58]:
matrix.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
matrix = np.array([(1,2,3), (4,5,6), (7,8,9), (10, 11, 12)])
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [63]:
np.random.random((2,2))

array([[0.12854742, 0.29798911],
       [0.23107879, 0.91191309]])

In [64]:
np.resize(matrix, (2,2))

array([[1, 2],
       [3, 4]])

Создание матрицы с помощью arange и reshape

In [65]:
new_matrix = np.arange(16).reshape(4,4)
new_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Создание специальных матриц

In [67]:
np.zeros((2,3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

Создание пустой матрици
> Внимание матрица не инициализирована -> может хранить мусор

In [72]:
np.empty((3,2))

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### Операции над матрицами

In [73]:
a = np.array([(1,2),(3,4)])
b = np.array([(5,6),(7,8)])

In [74]:
np.add(a,b)
a + b

array([[ 6,  8],
       [10, 12]])

In [75]:
np.subtract(a,b)
a - b

array([[-4, -4],
       [-4, -4]])

In [76]:
np.multiply(a,b)
a * b

array([[ 5, 12],
       [21, 32]])

In [77]:
np.divide(a,b)
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

Скалярное произведение

In [78]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [102]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [86]:
np.sqrt(matrix)
np.sin(matrix)
np.cos(matrix)
np.log(matrix)
np.exp(matrix)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

##### Axis (оси)

**Axis** - ось. 0 - ось строк; 1 - ось столбцов

![Axis Image](https://www.statology.org/wp-content/uploads/2022/06/numpyaxis1.jpg)

In [83]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.delete(matrix, 1, axis=0)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
np.delete(matrix, 1, axis=1)

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

При применении определенных функций NumPy, таких как np.mean(), max() и т.д. мы можем указать, по какой оси мы хотим получать значения.

Для axis=0 это озночает, что мы применяем функцию к каждому **столбцу** или ко всем значениям, которые встречаются по вертикали.

Для axis=1 это означает, что мы применям функцию к каждой **строке** или ко всем значениям по горизонтали.

In [92]:
matrix.sum()

78

In [88]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
print(matrix.max())
matrix.max(axis=0)  # Ищем наибольший элемент по каждой строке

12


array([10, 11, 12])

In [94]:
print(matrix.max())
matrix.max(axis=1)  # Ищем наибольший элемент по каждому столбцу

12


array([ 3,  6,  9, 12])

In [99]:
np.mean(matrix)
np.mean(matrix, axis=0) # среднее значение идет по строкам (1 + 4 + 7 + 10)/4 = 5.5

array([5.5, 6.5, 7.5])

In [101]:
np.mean(matrix, axis=1) # среднее значение идет по столбцам (1 + 2 + 3)/3 = 2

array([ 2.,  5.,  8., 11.])

In [107]:
np.concatenate((a,b), axis=1) # добавляем b к a как столбцы
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [108]:
np.concatenate((a,b), axis=0) # добавляем b к a как строки
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [109]:
np.split(matrix, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [113]:
np.split(matrix, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

#### Индексация

In [120]:
matrix = np.arange(1,10).reshape((3,3))
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
matrix[1,2] # 1 строка 2 столбец

6

In [124]:
matrix[2]       # 2 строка
matrix[:, 2]    # 2 столбец
matrix[1:3, 0:2]# 1 и 2 строки, 0 и 1 столбец

array([[4, 5],
       [7, 8]])

In [126]:
matrix[matrix > 2]

array([3, 4, 5, 6, 7, 8, 9])

#### Специальные операции

In [154]:
matrix = np.arange(1,10).reshape((3,3))
matrix[1,1] = 3
matrix

array([[1, 2, 3],
       [4, 3, 6],
       [7, 8, 9]])

In [133]:
matrix.T # транспанирование

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [130]:
matrix.flatten() # в массив

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.trace(matrix) # след матрицы

15

In [151]:
np.linalg.det(matrix) # определитель

0.0

In [141]:
np.linalg.matrix_rank(matrix) # ранк

2

In [155]:
np.linalg.inv(matrix) # обратная матрица

array([[-0.875     ,  0.25      ,  0.125     ],
       [ 0.25      , -0.5       ,  0.25      ],
       [ 0.45833333,  0.25      , -0.20833333]])

In [157]:
eigenvalues, eigenvectors = np.linalg.eig(matrix) # собственные числа и вектора

print("eigenvalues:", eigenvalues)
print()
print("eigenvectors:", eigenvectors)

eigenvalues: [15.54400375 -1.         -1.54400375]

eigenvectors: [[ 0.24005684  0.87287156 -0.32012138]
 [ 0.48011368 -0.21821789 -0.64024277]
 [ 0.84372008 -0.43643578  0.69829184]]


### Дополнительные возможности

In [159]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    com

In [ ]:
np.loadtxt('file.txt')                      # загрузка из тектового файла
np.genfromtxt('file.csv', delimiter=',')    # загрузка из csv
np.savetxt('file.txt', arr, delimiter=' ')    # запись в текстовый файл
np.savetxt('file.csv', arr, delimiter=',')  # запись в csv файл

## Полезные ссылки

* [NumPy](https://numpy.org/)
* [NumPy Cheet Sheet](https://www.dataquest.io/blog/numpy-cheat-sheet/)